package bridge

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
)

// Native-messaging host install for the CLI half of the K-055 dual-host — the
// mirror of the app's browser-bridge.ts install, but for a native Go binary
// (no Electron-as-node wrapper). We register com.skrptiq.cli_bridge so Chrome can
// spawn THIS binary in host mode on demand.

const (
	// NativeHostName is the CLI's native-messaging host id (the app owns app_bridge).
	NativeHostName = "com.skrptiq.cli_bridge"

	// PinnedExtensionID is the ENTIRE trust boundary alongside the 0600 socket —
	// the SAME pinned id as the app's manifest, which is what makes K-055
	// port-per-host routing return a CLI-engine invoke to the CLI's engine. Must
	// match skrptiq-extension's manifest key + the app's PINNED_EXTENSION_ID.
	PinnedExtensionID = "bnjefodmfiegaepelegdagnjkgdbfjpd"
)

// nativeHostManifest is the on-disk native-messaging host manifest.
type nativeHostManifest struct {
	Name           string   `json:"name"`
	Description    string   `json:"description"`
	Path           string   `json:"path"`
	Type           string   `json:"type"`
	AllowedOrigins []string `json:"allowed_origins"`
}

// buildNativeHostManifest builds the manifest object (pure/testable).
func buildNativeHostManifest(wrapperPath string) nativeHostManifest {
	return nativeHostManifest{
		Name:           NativeHostName,
		Description:    "Skrptiq CLI Browser Bridge (engine-host)",
		Path:           wrapperPath,
		Type:           "stdio",
		AllowedOrigins: []string{fmt.Sprintf("chrome-extension://%s/", PinnedExtensionID)},
	}
}

// nativeHostWrapperContent is the shell wrapper Chrome execs. Chrome cannot pass
// our `--mode host` via the manifest `path` (it appends the extension origin), so
// — like the app — the manifest points at a tiny wrapper that execs the binary in
// host mode. Pure/testable.
func nativeHostWrapperContent(cliBinaryPath string) string {
	return "#!/bin/sh\n" +
		"# Generated by Skrptiq (GH#866) — do not edit.\n" +
		fmt.Sprintf("exec %q __bridge --mode host\n", cliBinaryPath)
}

// chromeNativeMessagingDir is Chrome's per-user NativeMessagingHosts dir. Returns
// "" on unsupported platforms (Windows uses a registry key — deferred, §9.6).
func chromeNativeMessagingDir() string {
	home, _ := os.UserHomeDir()
	switch runtime.GOOS {
	case "darwin":
		return filepath.Join(home, "Library", "Application Support", "Google", "Chrome", "NativeMessagingHosts")
	case "linux":
		return filepath.Join(home, ".config", "google-chrome", "NativeMessagingHosts")
	default:
		return ""
	}
}

// wrapperDir is the stable per-user dir the CLI writes its host wrapper into.
func wrapperDir() string {
	home, _ := os.UserHomeDir()
	if runtime.GOOS == "darwin" {
		return filepath.Join(home, "Library", "Application Support", "skrptiq", "cli-bridge-host")
	}
	if xdg := os.Getenv("XDG_CONFIG_HOME"); xdg != "" {
		return filepath.Join(xdg, "skrptiq", "cli-bridge-host")
	}
	return filepath.Join(home, ".config", "skrptiq", "cli-bridge-host")
}

// nativeHostOpts overrides the resolved dirs/binary for tests.
type nativeHostOpts struct {
	nmDir      string // Chrome NativeMessagingHosts dir
	wrapperDir string // where the wrapper is written
	cliBinary  string // the skrptiq binary path baked into the wrapper
}

func (o *nativeHostOpts) resolve() (nmDir, wrapDir, binary string, err error) {
	nmDir = o.nmDir
	if nmDir == "" {
		nmDir = chromeNativeMessagingDir()
	}
	if nmDir == "" {
		return "", "", "", fmt.Errorf("native-messaging host install unsupported on this platform (Windows registry deferred)")
	}
	wrapDir = o.wrapperDir
	if wrapDir == "" {
		wrapDir = wrapperDir()
	}
	binary = o.cliBinary
	if binary == "" {
		binary, err = os.Executable()
		if err != nil {
			return "", "", "", fmt.Errorf("resolve CLI binary path: %w", err)
		}
	}
	return nmDir, wrapDir, binary, nil
}

// nativeHostPaths reports where install wrote its artefacts.
type nativeHostPaths struct {
	manifestPath string
	wrapperPath  string
}

// installNativeHost writes the wrapper (0700) + manifest into Chrome's
// NativeMessagingHosts dir. Idempotent (overwrites). Fails loud on an
// unsupported platform.
func installNativeHost(opts nativeHostOpts) (nativeHostPaths, error) {
	nmDir, wrapDir, binary, err := opts.resolve()
	if err != nil {
		return nativeHostPaths{}, err
	}
	if err := os.MkdirAll(wrapDir, 0o700); err != nil {
		return nativeHostPaths{}, fmt.Errorf("create wrapper dir: %w", err)
	}
	wrapperPath := filepath.Join(wrapDir, "cli-host")
	if err := os.WriteFile(wrapperPath, []byte(nativeHostWrapperContent(binary)), 0o700); err != nil {
		return nativeHostPaths{}, fmt.Errorf("write wrapper: %w", err)
	}
	if err := os.Chmod(wrapperPath, 0o700); err != nil {
		return nativeHostPaths{}, fmt.Errorf("chmod wrapper: %w", err)
	}
	if err := os.MkdirAll(nmDir, 0o755); err != nil {
		return nativeHostPaths{}, fmt.Errorf("create native-messaging dir: %w", err)
	}
	manifestPath := filepath.Join(nmDir, NativeHostName+".json")
	body, err := json.MarshalIndent(buildNativeHostManifest(wrapperPath), "", "  ")
	if err != nil {
		return nativeHostPaths{}, err
	}
	if err := os.WriteFile(manifestPath, append(body, '\n'), 0o644); err != nil {
		return nativeHostPaths{}, fmt.Errorf("write manifest: %w", err)
	}
	return nativeHostPaths{manifestPath: manifestPath, wrapperPath: wrapperPath}, nil
}

// uninstallNativeHost removes the manifest + wrapper (best-effort, reverse path).
func uninstallNativeHost(opts nativeHostOpts) {
	nmDir := opts.nmDir
	if nmDir == "" {
		nmDir = chromeNativeMessagingDir()
	}
	wrapDir := opts.wrapperDir
	if wrapDir == "" {
		wrapDir = wrapperDir()
	}
	if nmDir != "" {
		_ = os.Remove(filepath.Join(nmDir, NativeHostName+".json"))
	}
	_ = os.Remove(filepath.Join(wrapDir, "cli-host"))
}

// isNativeHostInstalled reports whether the manifest is present.
func isNativeHostInstalled(opts nativeHostOpts) bool {
	nmDir := opts.nmDir
	if nmDir == "" {
		nmDir = chromeNativeMessagingDir()
	}
	if nmDir == "" {
		return false
	}
	_, err := os.Stat(filepath.Join(nmDir, NativeHostName+".json"))
	return err == nil
}
