#!/usr/bin/env node
/**
 * regen-catalog.mjs — GH#866 / K-055.
 *
 * Mechanically derive the CLI bridge's vendored tool catalog from the FROZEN
 * single-source-of-truth in the skrptiq-extension repo
 * (companion/src/catalog.ts) — NOT a hand-maintained copy (that is the K-049
 * two-copies-drift class we avoid). The Go bridge loads the emitted JSON at
 * runtime AND the same file is the conformance golden, so runtime source and
 * the drift guard are one file.
 *
 * Output:
 *   internal/bridge/catalog.json             — the CATALOG array, verbatim data
 *   internal/bridge/catalog.provenance.json  — source repo/commit + catalog.ts
 *                                              sha256, so drift is detectable
 *
 * Usage:
 *   node scripts/regen-catalog.mjs [path-to-skrptiq-extension]
 *   (defaults to ../skrptiq-extension; SKRPTIQ_EXTENSION_DIR overrides)
 *
 * Requires esbuild (resolved from the extension's node_modules) to transpile the
 * TS SoT — a dev-time tool only; the shipped Go binary stays Node-free.
 */

import { createRequire } from "node:module";
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync, mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";

const extDir = resolve(
  process.argv[2] || process.env.SKRPTIQ_EXTENSION_DIR || "../skrptiq-extension",
);
const catalogTs = join(extDir, "companion", "src", "catalog.ts");
const outDir = resolve(new URL("../internal/bridge", import.meta.url).pathname);

function fail(msg) {
  console.error(`[regen-catalog] ${msg}`);
  process.exit(1);
}

let esbuild;
try {
  const req = createRequire(join(extDir, "package.json"));
  esbuild = await import(pathToFileURL(req.resolve("esbuild")).href);
} catch (err) {
  fail(
    `could not load esbuild from ${extDir}/node_modules — run \`pnpm install\` there first (${err?.message ?? err})`,
  );
}

let source;
try {
  source = readFileSync(catalogTs, "utf8");
} catch {
  fail(`catalog SoT not found at ${catalogTs} — pass the extension repo path`);
}

// Transpile+bundle catalog.ts (its imports are type-only, erased) to a temp ESM,
// import it, and read the CATALOG array — a faithful mechanical extraction.
const tmp = mkdtempSync(join(tmpdir(), "skrptiq-catalog-"));
const bundle = join(tmp, "catalog.mjs");
await esbuild.build({
  entryPoints: [catalogTs],
  bundle: true,
  format: "esm",
  platform: "neutral",
  outfile: bundle,
  logLevel: "silent",
});
const { CATALOG } = await import(pathToFileURL(bundle).href);
if (!Array.isArray(CATALOG) || CATALOG.length === 0) {
  fail("imported CATALOG is empty or not an array — SoT shape changed?");
}

const sha256 = createHash("sha256").update(source).digest("hex");
let commit = "unknown";
try {
  commit = execFileSync("git", ["-C", extDir, "rev-parse", "HEAD"], {
    encoding: "utf8",
  }).trim();
} catch {
  /* provenance commit is best-effort */
}

writeFileSync(join(outDir, "catalog.json"), JSON.stringify(CATALOG, null, 2) + "\n");
writeFileSync(
  join(outDir, "catalog.provenance.json"),
  JSON.stringify(
    {
      note: "Generated by scripts/regen-catalog.mjs — do not edit by hand. Re-run to update.",
      sourceRepo: "skrptiq/skrptiq-extension",
      sourceFile: "companion/src/catalog.ts",
      sourceCommit: commit,
      sourceSha256: sha256,
      toolCount: CATALOG.length,
      toolNames: CATALOG.map((t) => t.name),
    },
    null,
    2,
  ) + "\n",
);

console.error(
  `[regen-catalog] wrote ${CATALOG.length} tools (${CATALOG.map((t) => t.name).join(", ")}) from ${commit.slice(0, 7)}`,
);
